FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY SteamApps/SteamApps.csproj .
RUN dotnet restore SteamApps.csproj

COPY . .
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:6.0-aspnetcore-runtime AS runtime
WORKDIR /app
COPY --from=build /app/out ./

ENTRYPOINT ["dotnet run"]
