FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY SteamApps/SteamApps.csproj SteamApps/
RUN dotnet restore SteamApps/SteamApps.csproj
COPY . .
WORKDIR /src/SteamApps
RUN dotnet build SteamApps.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish SteamApps.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "SteamApps.dll"]
